date: "2025-12-22"
author: Quyu Kong
title: 'MobileWorld: Benchmarking Autonomous Mobile Agents in Agent-User Interactive, and MCP-Augmented Environments'
thumbnail: ""
link: https://huggingface.co/papers/2512.19432
summary: MobileWorld is a new benchmark for testing mobile agents, which is more challenging and realistic than the current leading benchmark, AndroidWorld. It has longer tasks, more cross-application interactions, and new task categories like user interaction and MCP-augmented tasks, and the best agents only achieved a 51.7% success rate in it....
opinion: placeholder
tags:
    - ML
