date: "2025-11-04"
author: Gyeom Hwangbo
title: 'LEGO-Eval: Towards Fine-Grained Evaluation on Synthesizing 3D Embodied   Environments with Tool Augmentation'
thumbnail: ""
link: https://huggingface.co/papers/2511.03001
summary: The authors present LEGO-Eval, a new evaluation framework for assessing the alignment between fine-grained instructions and generated 3D scenes, which outperforms existing methods by 0.41 F1 score. They also introduce LEGO-Bench, a benchmark for detailed instructions, revealing significant limitations in current generation methods....
opinion: placeholder
tags:
    - ML
