date: "2025-11-25"
author: Daniel Kienzle
title: 'Uplifting Table Tennis: A Robust, Real-World Application for 3D Trajectory and Spin Estimation'
thumbnail: ""
link: https://huggingface.co/papers/2511.20250
summary: This study presents a new two-step method to accurately track the 3D motion of a ping pong ball from regular videos, which is difficult due to real-world challenges. The method separates the problem into two tasks and uses a newly created dataset for training, resulting in a practical and robust application for analyzing ping pong ball trajectories and spin....
opinion: placeholder
tags:
    - ML
