date: "2025-12-04"
author: Nex-AGI Team
title: 'Nex-N1: Agentic Models Trained via a Unified Ecosystem for Large-Scale Environment Construction'
thumbnail: ""
link: https://huggingface.co/papers/2512.04987
summary: The paper presents a new method to create complex and diverse interactive environments for training large language models (LLMs) to behave as autonomous agents. The method, called Nex-N1, outperforms state-of-the-art open-source models and competes with proprietary ones in complex agentic tasks, and its source code and model weights are made available for further research....
opinion: placeholder
tags:
    - ML
