date: "2025-11-23"
author: Jian Yang
title: 'From Code Foundation Models to Agents and Applications: A Practical Guide to Code Intelligence'
thumbnail: ""
link: https://huggingface.co/papers/2511.18538
summary: This study offers a detailed guide on code Large Language Models (LLMs), exploring their life cycle and analyzing their capabilities. It identifies gaps between academic research and real-world code tasks, suggesting practical research directions....
opinion: placeholder
tags:
    - ML
