date: "2025-11-18"
author: Dwipam Katariya
title: 'FinTRec: Transformer Based Unified Contextual Ads Targeting and Personalization for Financial Applications'
thumbnail: ""
link: https://huggingface.co/papers/2511.14865
summary: The study presents FinTRec, a transformer-based framework designed to tackle practical challenges in real-time financial services recommendations, such as long-range user interactions and multiple interrelated products. FinTRec outperforms traditional tree-based models in both historic simulations and live tests, offering improved performance, reduced training costs, and better cross-product signal sharing....
opinion: placeholder
tags:
    - ML
